name: Node.js Backend CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # Specify the type of runner
    runs-on: self-hosted # Change to `self-hosted` only if you have a self-hosted runner set up

    strategy:
      matrix:
        node-version: [22.x] # Adjust versions according to your backend compatibility

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4

    # Step 2: Set up Node.js environment
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: npm ci

    # Step 4: Build the application (optional for backend, use if a build step is present)
    - name: Build Application
      run: npm run build --if-present

    # Step 5: Run tests (if tests are defined)
    - name: Run Builds
      run: npm run build

    # Step 6: Start the application (for validation or deployment purposes)
    - name: Start Application
      run: npm start
